### ISSUE TITLE
imgur links to .gifv's do not display through Show Image preview

### ISSUE THREAD

**Issue by lawrencecushman** [gabranches/Simpleddit#1]
![screenshot 2015-02-05 13 06 56](https://cloud.githubusercontent.com/assets/1784684/6066051/f3c7293c-ad37-11e4-83c6-872937371afb.png)

**Comment by AustinDizzy** [comment]
The cause of this is line(s) 59 to 62 in handlebars_helpers.js:

``` javascript
    else if (data.domain == "i.imgur.com")
    {
        return prefix + suffix;
    }
```

The image begins with `i.imgur.com` so it tries to put a video object (gifv is essentially a webm container) in an image object.

A case should be made for if `data.url` ends with `.gifv` and the domain is `i.imgur.com` to return a video tag with the gifv extension replaced with webm and mp4 sources for browser compatibility.

I'll submit a PR momentarily with the fix.

**Comment by gabranches** [comment]
Thanks, much appreciated! I should be able to put the fix live tonight.
