### ISSUE TITLE
Title's are not escaped.

### ISSUE THREAD

**Issue by allanhortle** [gabranches/Simpleddit#2]
![image](https://cloud.githubusercontent.com/assets/3760524/6070340/b7791dc0-addf-11e4-96e2-74c19348020c.png)

Should read:
Parse an image from an <input type="file"> tag into C# from ajax

**Comment by allanhortle** [comment]
Sick app by the way. Looking forward to seeing it progress :)

**Comment by erinclemmer** [comment]
can you link that url?

**Comment by allanhortle** [comment]
http://www.reddit.com/r/javascript/comments/2uvzv1/parse_an_image_from_an_input_typefile_tag_into_c

http://www.simplereddit.net/#javascript-2uvzv1

**Comment by erinclemmer** [comment]
Yeah, I can't seem to figure out how to do that. it comes in escaped, but is double parsed or something and goes back to normal code

**Comment by allanhortle** [comment]
It's pretty bad. I can execute random JS code if if wrap the title in a script tag. 

http://www.reddit.com/r/SimpleReddit/comments/2v589x/scriptalerttitle_parsing_testscript/
http://www.simplereddit.net/#simplereddit-2v589x

**Comment by erinclemmer** [comment]
The code executes right after it is retrieved from reddit, the <'s are escaped in the JSON, so it executes before I even have the chance to manipulate it

**Comment by allanhortle** [comment]
The titles are being unescaped by the handlebars helper. Make sure it returns a [SafeString](http://handlebarsjs.com/#html-escaping)

``` js
Handlebars.registerHelper("htmlHelper", function (data) {
   return new Handlebars.SafeString(htmlDecode(data));
});
```

 https://github.com/gvdasolutions/simplereddit/blob/master/handlebars_helpers.js#L20

I was going to just make a pull request, but after cloning the repo `main.php` doesn't exist. Is there a reason for this?

**Comment by erinclemmer** [comment]
I have no Idea, I think it includes the handlebars templates

**Comment by erinclemmer** [comment]
still not working.

**Comment by gabranches** [comment]
Hi, I added. main.php to the repo. All it does is pull the parameter from the url to redirect the user to the correct sub.

**Comment by erinclemmer** [comment]
oh,  ok, where are the templates?

**Comment by gabranches** [comment]
They should be in index.php

**Comment by gabranches** [comment]
Pushed Allan's changes live. Thanks!
