### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by MastermindJapan** [gabranches/Simpleddit#20]
Error when accessing website: 

"An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail"

**Comment by pascal-t** [comment]
Yeah it's a bummer. The feedback form is gone, too. Maybe he shut down the project. Considering that the last change was more than 6 years ago, I'm surprised it still works as good as it does.
But until we know more from @gabranches himself, you can easily host it yourself. Just install apache, php and clone the repo in the webroot. If you don't have a server or raspberry PI to host it, you can probably even host it in a VM or in the WSL.

**Comment by gabranches** [comment]
Hey all,

As @pascal-t said, yes I have not maintained this project for a very long time. At this time, I do not have plans to bring it back up. Please feel free to host it yourself if you'd like!

Best,
Gustavo
