### ISSUE TITLE
Cannot access subreddit groups via the url bar

### ISSUE THREAD

**Issue by allanhortle** [gabranches/Simpleddit#3]
I normally have a few webdev subreddits bookmarked for easy access. I can get to it through the search box, but it's more work.

```
http://www.simplereddit.net/javascript+webdev+programming+frontend
```

**Comment by orbweaver-** [comment]
This will be probably be best implemented after Oauth instead of cookies because they would go away after a few days

**Comment by erinclemmer** [comment]
I just realized what you meant, use this instead
`http://www.simplereddit.net/#javascript+webdev+programming+frontend`
