### ISSUE TITLE
Long reddit return url's are getting truncated.

### ISSUE THREAD

**Issue by allanhortle** [gabranches/Simpleddit#9]
![image](https://cloud.githubusercontent.com/assets/3760524/6098689/d74c25ae-b03a-11e4-90e8-513c809c7d0b.png)

http://www.simplereddit.net/#javscript+webdev+programming+frontend+pics

**Comment by erinclemmer** [comment]
That has to do with the way it splits the URL, I fixed it in my pull request

**Comment by gabranches** [comment]
This is live now. Thank you.
